apiVersion: v1
items:
  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.localtest-geth.dev.yml -o kube-localtest-geth-deployment.yaml -v
        kompose.service.expose: coordinator
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: coordinator
      name: coordinator
    spec:
      ports:
        - name: "8888"
          port: 8888
          targetPort: 8888
        - name: "5354"
          port: 5354
          targetPort: 5354
      selector:
        io.kompose.service: coordinator
    status:
      loadBalancer: {}
  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.localtest-geth.dev.yml -o kube-localtest-geth-deployment.yaml -v
        kompose.service.expose: organizer
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: organizer
      name: organizer
    spec:
      ports:
        - name: "8080"
          port: 8080
          targetPort: 8080
      selector:
        io.kompose.service: organizer
    status:
      loadBalancer: {}
  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.localtest-geth.dev.yml -o kube-localtest-geth-deployment.yaml -v
        kompose.service.expose: redis
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: redis
      name: redis
    spec:
      ports:
        - name: "6379"
          port: 6379
          targetPort: 6379
      selector:
        io.kompose.service: redis
    status:
      loadBalancer: {}
  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.localtest-geth.dev.yml -o kube-localtest-geth-deployment.yaml -v
        kompose.service.expose: testnet
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: testnet
      name: testnet
    spec:
      ports:
        - name: "5000"
          port: 5000
          targetPort: 5000
      selector:
        io.kompose.service: testnet
    status:
      loadBalancer: {}
  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.localtest-geth.dev.yml -o kube-localtest-geth-deployment.yaml -v
        kompose.controller.type: deployment
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: wallet
      name: wallet
    spec:
      ports:
        - name: "4444"
          port: 4444
          targetPort: 4444
      selector:
        io.kompose.service: wallet
    status:
      loadBalancer: {}
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.localtest-geth.dev.yml -o kube-localtest-geth-deployment.yaml -v
        kompose.service.expose: coordinator
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: coordinator
      name: coordinator
    spec:
      replicas: 1
      selector:
        matchLabels:
          io.kompose.service: coordinator
      strategy: {}
      template:
        metadata:
          annotations:
            kompose.cmd: kompose convert -f docker-compose.localtest-geth.dev.yml -o kube-localtest-geth-deployment.yaml -v
            kompose.service.expose: coordinator
            kompose.version: 1.26.0 (40646f47)
          creationTimestamp: null
          labels:
            io.kompose.service: coordinator
        spec:
          containers:
            - args:
                - bash
                - -c
                - nc -l -p 5354 && node /generator/dist/coordinator.js
              image: zkopru_node:latest
              name: coordinator
              ports:
                - containerPort: 8888
                - containerPort: 5354
              resources: {}
          restartPolicy: Always
    status: {}
  - apiVersion: networking.k8s.io/v1
    kind: Ingress
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.localtest-geth.dev.yml -o kube-localtest-geth-deployment.yaml -v
        kompose.service.expose: coordinator
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: coordinator
      name: coordinator
    spec:
      rules:
        - host: coordinator
          http:
            paths:
              - backend:
                  service:
                    name: coordinator
                    port:
                      number: 8888
                path: /
                pathType: Prefix
    status:
      loadBalancer: {}
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.localtest-geth.dev.yml -o kube-localtest-geth-deployment.yaml -v
        kompose.service.expose: organizer
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: organizer
      name: organizer
    spec:
      replicas: 1
      selector:
        matchLabels:
          io.kompose.service: organizer
      strategy: {}
      template:
        metadata:
          annotations:
            kompose.cmd: kompose convert -f docker-compose.localtest-geth.dev.yml -o kube-localtest-geth-deployment.yaml -v
            kompose.service.expose: organizer
            kompose.version: 1.26.0 (40646f47)
          creationTimestamp: null
          labels:
            io.kompose.service: organizer
        spec:
          containers:
            - args:
                - bash
                - -c
                - node /generator/dist/organizer/index.js
              image: zkopru_node:latest
              name: organizer
              ports:
                - containerPort: 8080
              resources: {}
          restartPolicy: Always
    status: {}
  - apiVersion: networking.k8s.io/v1
    kind: Ingress
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.localtest-geth.dev.yml -o kube-localtest-geth-deployment.yaml -v
        kompose.service.expose: organizer
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: organizer
      name: organizer
    spec:
      rules:
        - host: organizer
          http:
            paths:
              - backend:
                  service:
                    name: organizer
                    port:
                      number: 8080
                path: /
                pathType: Prefix
    status:
      loadBalancer: {}
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.localtest-geth.dev.yml -o kube-localtest-geth-deployment.yaml -v
        kompose.service.expose: redis
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: redis
      name: redis
    spec:
      replicas: 1
      selector:
        matchLabels:
          io.kompose.service: redis
      strategy: {}
      template:
        metadata:
          annotations:
            kompose.cmd: kompose convert -f docker-compose.localtest-geth.dev.yml -o kube-localtest-geth-deployment.yaml -v
            kompose.service.expose: redis
            kompose.version: 1.26.0 (40646f47)
          creationTimestamp: null
          labels:
            io.kompose.service: redis
        spec:
          containers:
            - image: redis
              name: redis
              ports:
                - containerPort: 6379
              resources: {}
          restartPolicy: Always
    status: {}
  - apiVersion: networking.k8s.io/v1
    kind: Ingress
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.localtest-geth.dev.yml -o kube-localtest-geth-deployment.yaml -v
        kompose.service.expose: redis
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: redis
      name: redis
    spec:
      rules:
        - host: redis
          http:
            paths:
              - backend:
                  service:
                    name: redis
                    port:
                      number: 6379
                path: /
                pathType: Prefix
    status:
      loadBalancer: {}
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.localtest-geth.dev.yml -o kube-localtest-geth-deployment.yaml -v
        kompose.service.expose: testnet
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: testnet
      name: testnet
    spec:
      replicas: 1
      selector:
        matchLabels:
          io.kompose.service: testnet
      strategy: {}
      template:
        metadata:
          annotations:
            kompose.cmd: kompose convert -f docker-compose.localtest-geth.dev.yml -o kube-localtest-geth-deployment.yaml -v
            kompose.service.expose: testnet
            kompose.version: 1.26.0 (40646f47)
          creationTimestamp: null
          labels:
            io.kompose.service: testnet
        spec:
          containers:
            - args:
                - sh
                - /proj/run_geth.sh
              image: zkopru_testnet_geth:latest
              name: testnet
              ports:
                - containerPort: 5000
              resources: {}
          restartPolicy: Always
    status: {}
  - apiVersion: networking.k8s.io/v1
    kind: Ingress
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.localtest-geth.dev.yml -o kube-localtest-geth-deployment.yaml -v
        kompose.service.expose: testnet
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: testnet
      name: testnet
    spec:
      rules:
        - host: testnet
          http:
            paths:
              - backend:
                  service:
                    name: testnet
                    port:
                      number: 5000
                path: /
                pathType: Prefix
    status:
      loadBalancer: {}
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.localtest-geth.dev.yml -o kube-localtest-geth-deployment.yaml -v
        kompose.controller.type: deployment
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: wallet
      name: wallet
    spec:
      replicas: 1
      selector:
        matchLabels:
          io.kompose.service: wallet
      strategy: {}
      template:
        metadata:
          annotations:
            kompose.cmd: kompose convert -f docker-compose.localtest-geth.dev.yml -o kube-localtest-geth-deployment.yaml -v
            kompose.controller.type: deployment
            kompose.version: 1.26.0 (40646f47)
          creationTimestamp: null
          labels:
            io.kompose.service: wallet
        spec:
          containers:
            - args:
                - bash
                - -c
                - sleep 10 && node /generator/dist/wallet.js
              image: zkopru_node:latest
              name: wallet
              ports:
                - containerPort: 4444
              resources: {}
          restartPolicy: Always
    status: {}
kind: List
metadata: {}

