apiVersion: v1
items:
  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.localtest-geth.yml -o ./dockerfiles/kube.localtest-geth.yaml
        kompose.service.expose: coordinator
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: coordinator
      name: coordinator
    spec:
      ports:
        - name: "8888"
          port: 8888
          targetPort: 8888
        - name: "5354"
          port: 5354
          targetPort: 5354
      selector:
        io.kompose.service: coordinator
    status:
      loadBalancer: {}
  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.localtest-geth.yml -o ./dockerfiles/kube.localtest-geth.yaml
        kompose.service.expose: organizer
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: organizer
      name: organizer
    spec:
      ports:
        - name: "8080"
          port: 8080
          targetPort: 8080
      selector:
        io.kompose.service: organizer
    status:
      loadBalancer: {}
  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.localtest-geth.yml -o ./dockerfiles/kube.localtest-geth.yaml
        kompose.service.expose: redis
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: redis
      name: redis
    spec:
      ports:
        - name: "6379"
          port: 6379
          targetPort: 6379
      selector:
        io.kompose.service: redis
    status:
      loadBalancer: {}
  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.localtest-geth.yml -o ./dockerfiles/kube.localtest-geth.yaml
        kompose.service.expose: testnet
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: testnet
      name: testnet
    spec:
      ports:
        - name: "5000"
          port: 5000
          targetPort: 5000
      selector:
        io.kompose.service: testnet
    status:
      loadBalancer: {}
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.localtest-geth.yml -o ./dockerfiles/kube.localtest-geth.yaml
        kompose.service.expose: coordinator
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: coordinator
      name: coordinator
    spec:
      replicas: 1
      selector:
        matchLabels:
          io.kompose.service: coordinator
      strategy: {}
      template:
        metadata:
          annotations:
            kompose.cmd: kompose convert -f docker-compose.localtest-geth.yml -o ./dockerfiles/kube.localtest-geth.yaml
            kompose.service.expose: coordinator
            kompose.version: 1.22.0 (955b78124)
          creationTimestamp: null
          labels:
            io.kompose.service: coordinator
        spec:
          containers:
            - args:
                - bash
                - -c
                - nc -l -p 5354 && node /proj/packages/generator/dist/coordinator.js
              image: sifnoc/zkopru_node:latest
              name: coordinator
              ports:
                - containerPort: 8888
                - containerPort: 5354
              resources: {}
          restartPolicy: Always
    status: {}
  - apiVersion: extensions/v1beta1
    kind: Ingress
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.localtest-geth.yml -o ./dockerfiles/kube.localtest-geth.yaml
        kompose.service.expose: coordinator
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: coordinator
      name: coordinator
    spec:
      rules:
        - host: coordinator
          http:
            paths:
              - backend:
                  serviceName: coordinator
                  servicePort: 8888
    status:
      loadBalancer: {}
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.localtest-geth.yml -o ./dockerfiles/kube.localtest-geth.yaml
        kompose.service.expose: organizer
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: organizer
      name: organizer
    spec:
      replicas: 1
      selector:
        matchLabels:
          io.kompose.service: organizer
      strategy: {}
      template:
        metadata:
          annotations:
            kompose.cmd: kompose convert -f docker-compose.localtest-geth.yml -o ./dockerfiles/kube.localtest-geth.yaml
            kompose.service.expose: organizer
            kompose.version: 1.22.0 (955b78124)
          creationTimestamp: null
          labels:
            io.kompose.service: organizer
        spec:
          containers:
            - args:
                - bash
                - -c
                - node /proj/packages/generator/dist/organizer.js
              image: sifnoc/zkopru_node:latest
              name: organizer
              ports:
                - containerPort: 8080
              resources: {}
          restartPolicy: Always
    status: {}
  - apiVersion: extensions/v1beta1
    kind: Ingress
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.localtest-geth.yml -o ./dockerfiles/kube.localtest-geth.yaml
        kompose.service.expose: organizer
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: organizer
      name: organizer
    spec:
      rules:
        - host: organizer
          http:
            paths:
              - backend:
                  serviceName: organizer
                  servicePort: 8080
    status:
      loadBalancer: {}
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.localtest-geth.yml -o ./dockerfiles/kube.localtest-geth.yaml
        kompose.service.expose: redis
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: redis
      name: redis
    spec:
      replicas: 1
      selector:
        matchLabels:
          io.kompose.service: redis
      strategy: {}
      template:
        metadata:
          annotations:
            kompose.cmd: kompose convert -f docker-compose.localtest-geth.yml -o ./dockerfiles/kube.localtest-geth.yaml
            kompose.service.expose: redis
            kompose.version: 1.22.0 (955b78124)
          creationTimestamp: null
          labels:
            io.kompose.service: redis
        spec:
          containers:
            - image: redis
              name: redis
              ports:
                - containerPort: 6379
              resources: {}
          restartPolicy: Always
    status: {}
  - apiVersion: extensions/v1beta1
    kind: Ingress
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.localtest-geth.yml -o ./dockerfiles/kube.localtest-geth.yaml
        kompose.service.expose: redis
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: redis
      name: redis
    spec:
      rules:
        - host: redis
          http:
            paths:
              - backend:
                  serviceName: redis
                  servicePort: 6379
    status:
      loadBalancer: {}
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.localtest-geth.yml -o ./dockerfiles/kube.localtest-geth.yaml
        kompose.service.expose: testnet
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: testnet
      name: testnet
    spec:
      replicas: 1
      selector:
        matchLabels:
          io.kompose.service: testnet
      strategy: {}
      template:
        metadata:
          annotations:
            kompose.cmd: kompose convert -f docker-compose.localtest-geth.yml -o ./dockerfiles/kube.localtest-geth.yaml
            kompose.service.expose: testnet
            kompose.version: 1.22.0 (955b78124)
          creationTimestamp: null
          labels:
            io.kompose.service: testnet
        spec:
          containers:
            - args:
                - sh
                - /proj/run_geth.sh
              image: sifnoc/zkopru_testnet:geth
              name: testnet
              ports:
                - containerPort: 5000
              resources: {}
          restartPolicy: Always
    status: {}
  - apiVersion: extensions/v1beta1
    kind: Ingress
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.localtest-geth.yml -o ./dockerfiles/kube.localtest-geth.yaml
        kompose.service.expose: testnet
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: testnet
      name: testnet
    spec:
      rules:
        - host: testnet
          http:
            paths:
              - backend:
                  serviceName: testnet
                  servicePort: 5000
    status:
      loadBalancer: {}
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.localtest-geth.yml -o ./dockerfiles/kube.localtest-geth.yaml
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: turner
      name: turner
    spec:
      replicas: 1
      selector:
        matchLabels:
          io.kompose.service: turner
      strategy: {}
      template:
        metadata:
          annotations:
            kompose.cmd: kompose convert -f docker-compose.localtest-geth.yml -o ./dockerfiles/kube.localtest-geth.yaml
            kompose.version: 1.22.0 (955b78124)
          creationTimestamp: null
          labels:
            io.kompose.service: turner
        spec:
          containers:
            - args:
                - bash
                - -c
                - sleep 60 && node /proj/packages/generator/dist/blockturner.js
              image: sifnoc/zkopru_node:latest
              name: turner
              resources: {}
          restartPolicy: Always
    status: {}
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.localtest-geth.yml -o ./dockerfiles/kube.localtest-geth.yaml
        kompose.controller.type: deployment
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: wallet
      name: wallet
    spec:
      replicas: 2
      selector:
        matchLabels:
          io.kompose.service: wallet
      strategy: {}
      template:
        metadata:
          annotations:
            kompose.cmd: kompose convert -f docker-compose.localtest-geth.yml -o ./dockerfiles/kube.localtest-geth.yaml
            kompose.controller.type: deployment
            kompose.version: 1.22.0 (955b78124)
          creationTimestamp: null
          labels:
            io.kompose.service: wallet
        spec:
          containers:
            - args:
                - bash
                - -c
                - sleep 10 && node /proj/packages/generator/dist/wallet.js
              image: sifnoc/zkopru_node:latest
              name: wallet
              resources: {}
    status: {}
kind: List
metadata: {}
