version: '3'

services:
  testnet:
    image: zkopru_testnet_ganache
    build:
      context: ../
      dockerfile: ./dockerfiles/Contract.dockerfile
    ports:
      - '5000:5000'
    command: ganache-cli --db=/data -i 20200406 -p 5000 --gasPrice 1 --gasLimit 12000000 --deterministic --host 0.0.0.0 --secure --blockTime 13
  coordinator:
    image: zkopru_node
    build:
      context: ../
      dockerfile: ./dockerfiles/Generator.dockerfile
    ports:
      - '8888:8888'
    depends_on:
      - 'testnet'
    command: bash -c "sleep 5 && node /generator/dist/coordinator.js"
  redis:
    image: redis
    ports:
      - '6379:6379'
  organizer:
    image: zkopru_node
    build:
      context: ../
      dockerfile: ./dockerfiles/Generator.dockerfile
    ports:
      - '8080:8080'
    depends_on:
      - 'redis'
      - 'coordinator'
    command: bash -c "sleep 10 && node /generator/dist/organizer.js"
  wallet:
    image: zkopru_node
    build:
      context: ../
      dockerfile: ./dockerfiles/Generator.dockerfile
    depends_on:
      - 'redis'
      - 'organizer'
    command: bash -c "sleep 15 && node /generator/dist/wallet.js"
