version: '3'

services:
  testnet:
    image: zkopru_testnet_ganache
    build:
      context: ../
      dockerfile: ./dockerfiles/Contract.dockerfile
    command: ganache-cli --db=/data -i 20200406 -p 5000 --gasPrice 1 --gasLimit 12000000 --deterministic --host 0.0.0.0 --secure --blockTime 13
  coordinator:
    image: zkopru_node
    build:
      context: ../
      dockerfile: ./dockerfiles/Generator.dockerfile
    depends_on:
      - 'testnet'
    command: bash -c "sleep 5 && node /generator/dist/coordinator.js"
  redis:
    image: redis
  organizer:
    image: zkopru_node
    build:
      context: ../
      dockerfile: ./dockerfiles/Generator.dockerfile
    depends_on:
      - 'redis'
      - 'coordinator'
    command: bash -c "sleep 10 && node /generator/dist/organizer/index.js"
  wallet:
    image: zkopru_node
    build:
      context: ../
      dockerfile: ./dockerfiles/Generator.dockerfile
    depends_on:
      - 'redis'
      - 'organizer'
    command: bash -c "sleep 15 && node /generator/dist/wallet.js"
