version: '3'

services:
  testnet:
    image: zkopru_testnet_geth
    build:
      context: ../
      dockerfile: dockerfiles/Contract.geth.dockerfile
    networks:
      - test
    labels:
      kompose.service.expose: testnet
    command: sh /proj/run_geth.sh
  coordinator:
    image: zkopru_node
    build:
      context: ../
      dockerfile: dockerfiles/Generator.dockerfile
    networks:
      - test
    depends_on:
      - 'testnet'
    labels:
      kompose.service.expose: coordinator
    command: >
      bash -c "nc -l -p 5354 &&
      node /generator/dist/coordinator.js"
  redis:
    image: redis
    networks:
      - test
    labels:
      kompose.service.expose: redis
  organizer:
    image: zkopru_node
    build:
      context: ../
      dockerfile: dockerfiles/Generator.dockerfile
    networks:
      - test
    depends_on:
      - 'redis'
      - 'coordinator'
    labels:
      kompose.service.expose: organizer
    command: bash -c "node /generator/dist/organizer/index.js"
  wallet:
    image: zkopru_node
    build:
      context: ../
      dockerfile: dockerfiles/Generator.dockerfile
    networks:
      - test
    depends_on:
      - 'redis'
      - 'organizer'
    labels:
      kompose.controller.type: deployment
    command: >
      bash -c "sleep 10 && node /generator/dist/wallet.js"

networks:
  test:
    name: stress-test